### ISSUE TITLE
Silencing progress bar during tests?

### ISSUE THREAD

**Issue by cblavier** [fuelen/owl#4]
Hey, thanks for this library I love building CLI apps with it!

I have written some tests with `capture_io` but I can't capture the progress bar output (I'd just like to silence it).
What would be the best way?

**Comment by fuelen** [comment]
Hi @cblavier 

Take a look at helper which is used by Owl to test progress bar https://github.com/fuelen/owl/blob/35b464cd4c4ca050e3420e7b3f48f7405530a885/test/support/virtual_live_screen.ex
What we do here - start a live screen server with fake IO device which sends content back, and pass its pid to progress bar using `live_screen_server` parameter. Currently, this parameter is not documented (we should fix this), but it is just a reference to livescreen server.

You can use the helper as is, or modify it and instead of sending content back, just ignore it and that's it.

**Comment by fuelen** [comment]
I have to think, maybe I can come up with something simpler for ignoring output. But, the solution above is the core and the most flexible, as it allows running tests isolated and in parallel

**Comment by cblavier** [comment]
working perfectly thanks 🙏
